### ISSUE TITLE
Remove margin left on solo player profile table

### ISSUE THREAD

**Issue by colodenn** [colodenn/beerpong-dashboard#55]
![image](https://user-images.githubusercontent.com/43729834/150637698-89544b49-fee5-473c-bc3e-fb7239a554b3.png)

Delete the empty div.

**Comment by RishiKumarRay** [comment]
Where in code can i find this?

**Comment by colodenn** [comment]
/src/components/stats/TablePersonal.tsx :84

**Comment by RishiKumarRay** [comment]
@colodenn  Do we have to change this <div className='flex items-center mr-2 w-12 h-12'> to <div className='flex items-center'>
